config/routes.rb
Bigotry::Application.routes.draw do
  resources :articles

  resources :events

  resources :sources

end

app/models/source.rb
class Source < ActiveRecord::Base
    has_many :articles
    has_many :events, :through => :articles
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
    @source = Source.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.json
  def new
    @source = Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render json: @source, status: :created, location: @source }
      else
        format.html { render action: "new" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.json
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to sources_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
	<div class="input">
      <%= f.text_field :name %>
	</div>
  </div>
  <div class="field">
    <%= f.label :url %>
	<div class="input">
      <%= f.text_field :url %>
	  </div>
  </div>
  <div class="field">
    <%= f.label :daylife_id %>
	<div class="input">
      <%= f.text_field :daylife_id %>	  
	</div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<h1>Listing sources</h1>

<table class="zebra-striped">
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Daylife</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sources.each do |source| %>
  <tr>
    <td><%= source.name %></td>
    <td><%= source.url %></td>
    <td><%= source.daylife_id %></td>
    <td><%= link_to 'Show', source %></td>
    <td><%= link_to 'Edit', edit_source_path(source) %></td>
    <td><%= link_to 'Destroy', source, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Source', new_source_path, :class => "btn primary" %> 

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @source.name %>
</p>

<p>
  <b>Url:</b>
  <%= @source.url %>
</p>

<p>
  <b>Daylife:</b>
  <%= @source.daylife_id %>
</p>


<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>